# 参考 http://www.tuicool.com/articles/veUjQba
# Web容器配置
server:
  port: 7777
#热部署
spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      custom:
            hosts: localhost
            ports: 27017
            database: stock
            authentication-database: admin
            max-connections-per-host: 20
            min-connections-per-host: 1
#      host: localhost
#      port: 27017
#      database: stock
#是否开启swagger (true/false)
swagger:
  enable: true
