# 参考 http://www.tuicool.com/articles/veUjQba
# Web容器配置
server:
  port: 7777
#热部署
spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stock
#是否开启swagger (true/false)
swagger:
  enable: true




